
OUT_LIB = pix5input



CLSS = Input Action InputEventHandler

HDRS = pix5input.h JoyAxis.h JoyButton.h JoyHat.h Joystick.h Key.h Keyboard.h Mouse.h keys.h

SRCS = init.cc


PKGS  = sdl2

PIXLIBS = core


include ../Rules.make

