
OUT_LIB = pix5core



CLSS = Error CoreEventHandler Log Thread Job JobThread ThreadPool Cache

HDRS  = pix5core.h errors.h Math.h FIFO.h List.h SortedList.h Str.h
HDRS += Mutex.h Condition.h Barrier.h RWLock.h

SRCS  = dbg.cc get_ms.cc init.cc load_file.cc



PKGS  = sdl2



include ../Rules.make

