
OUT_LIB = pix5core



CLSS  = Error CoreEventHandler Log Thread Job JobThread ThreadPool Cache
CLSS += IO IOSource IOSourceUnix FileUnix
CLSS += RNG GZip

HDRS  = pix5core.h errors.h Math.h FIFO.h List.h SortedList.h Str.h
HDRS += Mutex.h Condition.h Barrier.h RWLock.h Buffer.h
HDRS += FilePath.h FileAccess.h File.h FileEntry.h MountEntry.h

SRCS  = dbg.cc get_ms.cc init.cc



PKGS  = sdl2 zlib



include ../Rules.make

