
OUT_LIB = pix5gfx



CLSS = Display Font Glyph Renderer ImmRenderer VBORenderer ShaderRenderer TextFormat Texture GfxEventHandler VideoData

HDRS = pix5gfx.h Color.h Rect.h RenderElement.h TextAlign.h VideoMode.h VideoModeType.h

SRCS = init.cc

DATA = data/vs.glsl data/fs.glsl data/LiberationSans-Regular.ttf


PKGS  = sdl2 SDL2_image gl glew freetype2

PIXLIBS = core input


include ../Rules.make

