
OUT_LIB = pix5net



CLSS = Net NetBuffer UdpSocket EndPoint UdpEndPoint UdpQueue UdpOutQueue UdpInQueue NetMessage

HDRS = pix5net.h SockAddr.h NetPacket.h EndPointState.h

SRCS = init.cc


PKGS = 


include ../Rules.make


